config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             controllers: {
               sessions: 'users/sessions',
               registrations: 'users/registrations',
               passwords: 'users/passwords',
               confirmations: 'users/confirmations',
               omniauth_callbacks: 'users/omniauth_callbacks'
             }

  resources :users, only: [:index, :show]
  get '/settings', to: 'users#settings', as: 'settings'

  resources :registered_applications,
            only: [:index, :show, :new, :create, :edit, :update, :destroy]

  root 'pages#welcome'
  get  'about', to: 'pages#about'
  get '/welcome/new', to: 'pages#welcome_new', as: 'welcome_new'
  get '/welcome/back', to: 'pages#welcome_back', as: 'welcome_back'

  namespace :api, defaults: { format: :json } do
    match '/events', to: 'events#preflight', via: [:options]
    resources :events, only: [:create]
  end

end

app/models/registered_application.rb
#
class RegisteredApplication < ActiveRecord::Base
  has_many :events, dependent: :destroy
  belongs_to :user

  validates :name, length: { minimum: 2 }, presence: true
  # Note: our form entry logic will prepend upto 11 chars
  # to the entered url, so the first 11 are a given,
  # i.e.'http://wwww.<userEntry>'
  validates :url, length:  { minimum: 11 + 8 }, presence: true
end

app/controllers/registered_applications_controller.rb
#
class RegisteredApplicationsController < ApplicationController
  before_action :make_view_helper
  before_filter :authenticate_user!

  # A frequent practice is to place the standard CRUD actions in each controller
  # in the following order:
  #   index, show, new, edit, create, update and destroy.
  #
  def index
    @view.apps = RegisteredApplication.where('user_id = ?', current_user.id)
    authorize @view.apps
    # Response: Controller will forward_to
    #           /views/registered_applications/index.html.erb with @view
  end

  def show
    @view.app = RegisteredApplication.find(params[:id])
    authorize @view.app
    # { ":bath:"=>1, ":football:"=>1, ":mahjong:"=>1, ":musical_keyboard:"=>1,
    #   ":saxophone:"=>1, ":slot_machine:"=>1
    # }
    # @view.event_group_counts =
    #  @view.app.events.group(:name).reorder('name ASC').count
    # @view.events = @view.app.events.group_by(&:name)
    # Response: Controller will forward_to
    #           /views/registered_applications/show.html.erb with @view
  end

  def new
    authorize RegisteredApplication
    @view.app = RegisteredApplication.new
    # Response: Controller will forward_to
    #           /views/registered_applications/new.html.erb with @view
    # Note: clicking on the form submit button will POST to create()
  end

  # Note: we get here from a submit button via the new view.
  def create
    authorize RegisteredApplication
    @view.app = RegisteredApplication.new(submitted_params_whitelist)
    @view.app.url = fixup_url
    @view.app.user = @view.current_user

    if @view.app.save
      # Response: tell browser to show this new registered site.
      redirect_to @view.app, notice: 'Site was saved successfully.'
    else
      # Response: redisplay the edit form with error msgs.
      flash.now[:alert] = 'Error creating registered site. Please try again.'
      render :new
    end
  end

  def edit
    @view.app = RegisteredApplication.find(params[:id])
    authorize @view.app
    # Response: Controller will forward_to
    #           /views/registered_applications/edit.html.erb
    #           with @view.
    # Note: clicking on the form submit button will POST to update()
  end

  # Note: we get here from a submit button via the edit view.
  def update
    @view.app = RegisteredApplication.find(params[:id])
    authorize @view.app
    @view.app.assign_attributes(submitted_params_whitelist)

    # Response: redirect to or forward_to a view with msgs
    if @view.app.save
      flash[:notice] = 'Registered site was updated'
      # Display the show page for the registered site we just edited.
      redirect_to @view.app
    else
      flash.now[:alert] = 'Error saving Registered Site. Please try again.'
      render :edit
    end
  end

  def destroy
    @view.app = RegisteredApplication.find(params[:id])
    authorize @view.app
    # Response: redirect to or forward_to to a view.
    if @view.app.destroy
      flash[:notice] = "\"#{@view.app.name}\" was deleted successfully."
      # Display list of registered sites for this user.
      redirect_to action: :index
    else
      flash.now[:alert] = 'There was an error deleting this Registered Site.'
      render :show
    end
  end

  # Decide where back button takes us.
  def page_back_button_path
    registered_applications_path
  end

  private

  def make_view_helper
    @view = ApplicationHelper::View.new(self, RegisteredApplication.new)
  end

  def submitted_params_whitelist
    params.require(:registered_application).permit(:name, :url)
  end

  # Given user input of a partial url, convert to absolute url.
  def fixup_url
    unless @view.app.url.starts_with?('http')
      unless @view.app.url.starts_with?('www')
        @view.app.url = 'www.' << @view.app.url
      end
      @view.app.url = 'http://' << @view.app.url
    end
    @view.app.url
  end
end

app/helpers/registered_applications_helper.rb
module RegisteredApplicationsHelper
end

app/views/registered_applications/_index_page_header.html.erb
<div class="row" style="margin-bottom: 30px;">
  <div class="col-md-2">
  </div>
  <div class="col-md-8 css-page-title">
    <div class="media">
      <div class="media-body">
        <h2 class="media-heading text-center"><%= @view.locals[:title] %></h2>
      </div>
    </div>
  </div>
  <div class="col-md-2 css-header-links">
    <% if true #policy(RegisteredApplication).create? && @view.rpt_app[:include_new_app] %>
      <%= link_to 'Register new Site', new_registered_application_path, class: 'btn btn-xs btn-primary pull-right' %>
    <% end %>
  </div>
</div>

app/views/registered_applications/_new_edit_form.html.erb
<div class="css-new-edit-form">
  <%= form_for @view.app  do |f| %>

    <%= f.label :name %><br />
    <%= f.text_field :name, autofocus: true, class: 'form-control', placeholder: 'Enter Site name' %>

    <%= f.label "#{'Full url'}" %><br />
    <%= f.text_field :url, rows: 2, class: 'form-control', placeholder: 'Enter full Site url, i.e. http://www.example.com' %>

    <div class="css-actions">
      <%= f.submit(@view.app.new_record? ? 'Register App' : 'Update Registration', class: 'btn btn-primary') %>
    </div>
  <% end %>
</div>

app/views/registered_applications/_new_edit_page.html.erb
<header>
  <div class="row">
    <div class="col-md-8 css-page-title">
      <div class="media">
        <div class="media-body">
          <h2 class="media-heading"><%= @view.locals[:title] %></h2>
        </div>
      </div>
    </div>
  </div>
</header>

<main>
  <div class="row">
    <div class="col-md-4">
      <p>FAQs about registering a new site:</p>
      <ul>
        <li>Make sure ..............</li>
        <li>And also .................</li>
        <li>Besides ..................</li>
      </ul>
    </div>
    <div class="col-md-4">
      <%= render partial: 'shared/errors', locals: @view.locals = { obj: @view.app } %>
      <%= render partial: 'new_edit_form' %>
    </div>
  </div>
</main>

app/views/registered_applications/_registered_app.html.erb
<div class="row css-regd-app-container" style="background: white;">

  <div class="col-md-8">
    <div class="media">
      <div class="media-body">
        <h4 class="media-heading">
            <span class="css-regd-app-name" style="overflow: hidden; text-decoration: underline;">
              <%= link_to @view.locals[:app].name,
                          registered_application_path(@view.locals[:app]),
                          title: "Created by: #{@view.locals[:app].user.name}" %>
            <span>
            <span style="color: black; font-weight: bold; ext-decoration: none;">&nbsp;at&nbsp;</span>
            <span class="css-regd-app-url" style="overflow: hidden; text-decoration: underline;">
              <%= link_to @view.locals[:app].url, @view.locals[:app].url, target: '_blank' %>
            <span>
        </h4>
      </div>
    </div>
  </div>

  <div class="col-md-4">
    <div class="media">
      <div class="media-body">
        <h4 class="media-heading">
          <% if true #policy(props[:bookmark]).destroy? && rpt_bmk(props)[:include_delete] %>
            <span class="pull-right css-regd-app-action" style="padding-top: 4px; padding-right: 4px;">
              <%= link_to 'Remove', @view.locals[:app], method: :delete,
                          class: 'btn btn-xs btn-danger',
                          data: {confirm: 'Are you sure you want to delete this site?'} %>
            </span>
          <% end %>
          <% if true #policy(props[:bookmark]).edit? && rpt_bmk(props)[:include_edit] %>
            <span class="pull-right css-regd-app-action" style="padding-top: 4px; padding-right: 4px;">
              <%= link_to 'Edit', edit_registered_application_path(@view.locals[:app]),
                          class: 'btn btn-xs btn-success' %>
            </span>
          <% end %>
        </h4>
      </div>
    </div>
  </div>

</div>

app/views/registered_applications/_show_page_header.html.erb
<div class="row">
  <div class="col-md-2">
  </div>
  <div class="col-md-8 css-page-title">
    <div class="media">
      <div class="media-body">
        <h2 class="media-heading text-center"><%= @view.locals[:app].name %></h2>
      </div>
    </div>
  </div>
  <div class="col-md-2 css-header-links">
    <% if true #policy(props[:bookmark]).destroy? && rpt_bmk(props)[:include_delete] %>
      <span class="pull-right css-regd-app-action" style="padding-top: 4px; padding-right: 4px;">
        <%= link_to 'Remove', @view.locals[:app], method: :delete,
                    class: 'btn btn-xs btn-danger',
                    data: {confirm: 'Are you sure you want to delete this site?'} %>
      </span>
    <% end %>
    <% if true #policy(props[:bookmark]).edit? && rpt_bmk(props)[:include_edit] %>
      <span class="pull-right css-regd-app-action" style="padding-top: 4px; padding-right: 4px;">
        <%= link_to 'Edit', edit_registered_application_path(@view.locals[:app]),
                    class: 'btn btn-xs btn-success' %>
      </span>
    <% end %>
  </div>
</div>

<div class="row" style="margin-bottom: 30px;">
  <div class="col-md-2">
  </div>
  <div class="col-md-8 css-site-url">
    <div class="media">
      <div class="media-body">
        <h4 class="media-heading text-center">
            <span class="css-regd-app-url" style="overflow: hidden; text-decoration: underline;">
              <%= link_to @view.locals[:app].url, @view.locals[:app].url, target: '_blank' %>
            <span>
        </h4>
      </div>
    </div>
  </div>
  <div class="col-md-2">
  </div>
</div>

app/views/registered_applications/edit.html.erb
<%= render partial: 'new_edit_page',
           locals: @view.locals = { title: 'Edit Registered Site' }
%>

app/views/registered_applications/index.html.erb
<header class="css-body-header">
  <%= render partial: 'index_page_header',
             locals: @view.locals = { title: 'My Monitored Sites' }
  %>
</header>

<main class="css-body-main">
  <% @view.apps.each_with_index do |app, index| %>
    <%= render partial: 'registered_app',
               locals: @view.locals = { app: app, apps_index: index }
    %>
  <% end %>
</main>

app/views/registered_applications/new.html.erb
<%= render partial: 'new_edit_page',
           locals: @view.locals = { title: 'Register a new Site' }
%>

app/views/registered_applications/show.html.erb
<header class="css-body-header">
  <%= render partial: 'show_page_header',
             locals: @view.locals = { app: @view.app, apps_index: 0 } %>
</header>

<main class="css-body-main">

  <%= render partial: '/events/styles/pie_chart_rpt_header' %>
  <%= render partial: '/events/styles/pie_chart_event' #,
      #       locals: @view.locals = { data: @view.event_group_counts }
  %>

  <%= render partial: '/events/styles/line_chart_rpt_header' %>
  <%= render partial: '/events/styles/line_chart_event' %>

  <%= render partial: '/events/styles/column_rpt_header' %>
  <% # @view.event_group_counts.each do |name, count| %>
  <% @view.app.events.group(:name).reorder('name ASC').count.each do |name, count| %>
    <%= render partial: '/events/styles/column_event',
               locals: @view.locals =
                 { name: name, count: count }
    %>
  <% end %>

</main>