config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             controllers: {
               sessions: 'users/sessions',
               registrations: 'users/registrations',
               passwords: 'users/passwords',
               confirmations: 'users/confirmations',
               omniauth_callbacks: 'users/omniauth_callbacks'
             }

  resources :users, only: [:index, :show]
  get '/settings', to: 'users#settings', as: 'settings'

  resources :registered_applications,
            only: [:index, :show, :new, :create, :edit, :update, :destroy]

  root 'pages#welcome'
  get  'about', to: 'pages#about'
  get '/welcome/new', to: 'pages#welcome_new', as: 'welcome_new'
  get '/welcome/back', to: 'pages#welcome_back', as: 'welcome_back'

  namespace :api, defaults: { format: :json } do
    match '/events', to: 'events#preflight', via: [:options]
    resources :events, only: [:create]
  end

end

app/views/layouts/_page_footer.html.erb
<!--  # ======== Begin: PAGE FOOTER -global- ========== -->
<footer class="css-page-footer">
  <header>
    <div class="container">
      <%= link_to 'Back', @view.back_path, class: 'btn btn-xs btn-primary' %>
    </div>
    <hr>
  </header>
  <nav>
    <div class="container">
      <p class="text-muted">
        Created by
        <a href="#"
           data-toggle="popover"
           title="A student at Block.io"
           data-placement="top"
           data-trigger="hover"
           data-html="true"
           data-content="<img src='https://cdn-photos.bloc.io/medium/2317655/photo.JPG?1450380571'>"
          >A student at Block.io
        </a>
        <% #who is on %>
        <% #= link_to 'LinkedIn', 'https://www.linkedin.com/in/raynovarina' %>
      </p>
    </div>
  </nav>
</footer>
<!-- # ======== End: PAGE FOOTER - global ========== -->

app/views/layouts/_page_header.html.erb
<!-- # ======== Begin: PAGE HEADER -global- ========== -->
<header class="css-page-header">
  <!-- # == Begin: Page Header Navigation - Navbar, inverse == -->
  <nav>
    <div class="navbar navbar-inverse">
      <div class="container">
        <%= render 'layouts/page_header_navbar_left' %>
        <%= render 'layouts/page_header_navbar_right' %>
      </div>
    </div>
  </nav>
  <!-- # ======== End: Page Header Navigation == -->
</header>
<!-- # ======== End: PAGE HEADER -global- ========== -->

app/views/layouts/_page_header_navbar_left.html.erb
<div class="css-navbar-left">
  <% if @view.user_signed_in? %>
    <div class="css-navbar-header">
      <%= link_to 'Blocmetrics', root_path, class: 'navbar-brand' %>
    </div>
    <ul class="nav navbar-nav">
      <li><%= link_to user_path(@view.current_user) do %>
        <i class="glyphicon glyphicon-home"> </i>&nbsp; Home<% end %>
      </li>
      <li><%= link_to about_path do %>
        <i class="glyphicon glyphicon-info-sign"> </i>&nbsp; About<% end %>
      </li>
      <li><%= link_to edit_user_registration_path(@view.current_user),
        title: "#{@view.current_user.name} (#{@view.current_user.email})" do %>
        <i class="glyphicon glyphicon-user"> </i>&nbsp;
        <span class="css-user-name">
          <%= "#{@view.current_user.email.split('@').first[0,14]}" %>
        </span><% end %>
      </li>
    </ul>
  <% else %>
    <div class="css-navbar-header">
      <%= link_to 'Blocmetrics', root_path, class: 'navbar-brand' %>
    </div>
    <ul class="nav navbar-nav">
      <li><%= link_to about_path do %>
        <i class="glyphicon glyphicon-info-sign"> </i>&nbsp; About<% end %>
      </li>
    </ul>
  <% end %>
</div>

app/views/layouts/_page_header_navbar_right.html.erb
<div class="css-navbar-right">
  <ul class="nav navbar-nav pull-right">
    <% if @view.user_signed_in? %>
      <% if policy(RegisteredApplication).index? %>
        <li><%= link_to 'My Sites',
                registered_applications_path,
                class: 'css-apps-link' %></li>
        <li><%= link_to '|', '' %></li>
      <% end %>
        <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
      <% if policy(User).edit? %>
        <li><%= link_to '|', '' %></li>
        <li><%= link_to settings_path,
                title: "Settings" do %>
                <i class="glyphicon glyphicon-cog glyph-1-5x"> </i>&nbsp;<% end %>
      <% end %>          
        </li>
    <% else %>
        <li><%= link_to 'Sign In', new_user_session_path %></li>
        <li><%= link_to '|', '' %></li>
        <li><%= link_to 'Sign Up', new_user_registration_path %></li>
    <% end %>
  </ul>
</div>

app/views/layouts/_page_main.html.erb
<!-- # ======= Begin: PAGE MAIN -global- ===== -->
<main class="css-page-main" >
  <!-- # == Begin: PAGE MAIN HEADER -global- -->
  <header>
    <!-- # == Begin: PAGE MAIN HEADER messages -global- -->
    <section>
      <div class="container css-flash-messages">
        <!-- Begin: Render Flash messages -->
        <%= render 'shared/page_main_header_flash_messages' %>
        <!-- End: Render Flash messages -->
        <!-- Optional: Other general messages. -->
        <% if content_for?(:page_main_header_other_messages) %>
          <!-- # == Begin: yield :Page Header Other Messages == -->
          <%= yield :page_main_header_other_messages %>
          <!-- # == End: yield :Page Header Other Messages == -->
        <% end %>
      </div>
    </section>
    <!-- # == End: PAGE MAIN HEADER messages -global- -->
  </header>
  <!-- # == End: PAGE MAIN HEADER -global- -->

  <!-- # == Begin: PAGE MAIN BODY -Global- -->
  <main>
    <!-- # == Begin: PAGE MAIN BODY container - Jumbotron == -->
    <div class="jumbotron">
      <div class="container css-body">
        <!-- # == Begin: yield :Page Main Body Content AtLast -Default- == -->
        <%= yield %>
        <!-- # == End: yield :Page Main Body Content AtLast -Default- == -->
      </div>
  </div>
  <!-- # == End: PAGE MAIN BODY container - Jumbotron == -->
  </main>
  <!-- # == End: PAGE MAIN BODY -Global- -->

  <!-- # == Begin: PAGE MAIN FOOTER -optional- -->
  <footer>
    <% if content_for?(:page_main_footer) %>
      <!-- # == Begin: yield :Page Main Footer == -->
      <%= yield :page_main_footer %>
      < !-- # == End: yield :Page Main Content Footer == -->
    <% end %>
    <!-- # == End: PAGE MAIN FOOTER -optional- -->
  </footer>
</main>
<!-- # == End: PAGE MAIN -global- == -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <!-- ==== Begin: HTML HEAD TAG === -->
  <meta charset="utf-8">
  <title>Blocmetrics</title>
  <% # Rails assest pipeline per: http://guides.rubyonrails.org/asset_pipeline.html %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <% # Per: https://github.com/ankane/chartkick#installation
     # And add the JavaScript files to your views. These files must be included
     # before the helper methods.
     # For Google Charts, use:
  %>
  <%= javascript_include_tag "https://www.google.com/jsapi", "chartkick" %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <% # Popovers must be initialized with jQuery: select the specified element
     # and call the popover() method.
     # per: http://www.w3schools.com/bootstrap/bootstrap_popover.asp
  %>
  <% #<script>
    #$(document).ready(function(){
    #  $('[data-toggle="popover"]').popover();
    #});
  #</script>
  %>
  <%= csrf_meta_tags %>
  <!-- ==== End: HTML HEAD TAG === -->
</head>
<body>


<% # ===== Blocmarks Page LAYOUT: ====   %>
<div class="css-<%= @view.name %>" >
<% # Note: default/global content can be override via content_for/yeild hooks %>
<% #------------------------------------------------------- %>
<% # Section0: (CSS: doc#header) -Global- %>
  <% # <header> Page Header  %>
  <%= render 'layouts/page_header' %>
   <% # <nav> Page Header navigation  %>
<% #------------------------------------------------------- %>
<% # Section1: (CSS: doc#main) -Global- %>
  <% # <main> Page Content  %>
  <%= render 'layouts/page_main' %>
    <% #---------------------------------- %>
    <% # <header> Page Main Content Header  %>
      <% # <section> Page Main Content messages -Global-  %>
    <% #---------------------------------- %>
    <% # <main> Page Main Content Body -Global- %>
      <% # <header> Page Main Content Body Header -Optional-  %>
        <% # <nav> Page Main Content navigation  %>
      <% # <main> Page Main Content Body -Optional- %>
      <% # <footer> Page Main Content Footer -Optional- %>
        <% # <nav> Page Main Content navigation  %>
    <% #---------------------------------- %>
    <% # <footer> Page Main Content Footer -Optional- %>
      <% # <nav> Page Main Content navigation  %>
<% #------------------------------------------------------- %>
<% # Section2: (CSS: doc#footer) Global %>
  <% # <footer> Page Footer %>
  <%= render 'layouts/page_footer' %>
    <% # <nav> Page Footer navigation  %>
<% #------------------------------------------------------- %>
</div>
</body>
</html>